import type { Preset, HistoryEntry } from './types';

export const COMMUNITY_PRESETS: Preset[] = [
  {
    id: 'community-1',
    name: 'Deep Focus',
    description: 'Rain and brown noise for deep concentration sessions',
    mix: [
      { soundId: 'rain', volume: 0.7 },
      { soundId: 'brown', volume: 0.4 },
    ],
    tags: ['focus', 'productivity'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    isCommunity: true,
    author: 'alex_writes',
    playCount: 2841,
  },
  {
    id: 'community-2',
    name: 'Cozy Evening',
    description: 'Crackling fire and gentle rain for a relaxing night in',
    mix: [
      { soundId: 'fire', volume: 0.65 },
      { soundId: 'rain', volume: 0.35 },
      { soundId: 'wind', volume: 0.2 },
    ],
    tags: ['relax', 'evening', 'cozy'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    isCommunity: true,
    author: 'marisol_r',
    playCount: 5623,
  },
  {
    id: 'community-3',
    name: 'Morning Birds',
    description: 'Wake up to a peaceful forest morning',
    mix: [
      { soundId: 'birds', volume: 0.75 },
      { soundId: 'forest', volume: 0.5 },
      { soundId: 'wind', volume: 0.15 },
    ],
    tags: ['morning', 'nature', 'energize'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    isCommunity: true,
    author: 'dawei_k',
    playCount: 1234,
  },
  {
    id: 'community-4',
    name: 'Café Sessions',
    description: 'Coffee shop ambience for productive work anywhere',
    mix: [
      { soundId: 'coffee', volume: 0.8 },
      { soundId: 'piano', volume: 0.3 },
    ],
    tags: ['focus', 'cafe', 'work'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    isCommunity: true,
    author: 'nomad_dev',
    playCount: 9102,
  },
  {
    id: 'community-5',
    name: 'Ocean Meditation',
    description: 'Waves and wind for mindfulness and meditation',
    mix: [
      { soundId: 'ocean', volume: 0.9 },
      { soundId: 'wind', volume: 0.25 },
    ],
    tags: ['meditation', 'calm', 'nature'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    isCommunity: true,
    author: 'zara_m',
    playCount: 7451,
  },
  {
    id: 'community-6',
    name: 'Storm at Sea',
    description: 'Powerful thunderstorm over rolling ocean waves',
    mix: [
      { soundId: 'thunder', volume: 0.6 },
      { soundId: 'ocean', volume: 0.7 },
      { soundId: 'wind', volume: 0.5 },
      { soundId: 'rain', volume: 0.4 },
    ],
    tags: ['dramatic', 'focus', 'epic'],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    isCommunity: true,
    author: 'thor_s',
    playCount: 3317,
  },
];

export const MOCK_HISTORY: HistoryEntry[] = [
  {
    id: 'h-1',
    presetName: 'Deep Focus',
    presetId: 'community-1',
    mix: [
      { soundId: 'rain', volume: 0.7 },
      { soundId: 'brown', volume: 0.4 },
    ],
    duration: 25 * 60,
    startedAt: Date.now() - 1000 * 60 * 60 * 2,
    endedAt: Date.now() - 1000 * 60 * 60 * 1,
  },
  {
    id: 'h-2',
    presetName: 'Cozy Evening',
    presetId: 'community-2',
    mix: [
      { soundId: 'fire', volume: 0.65 },
      { soundId: 'rain', volume: 0.35 },
    ],
    duration: 45 * 60,
    startedAt: Date.now() - 1000 * 60 * 60 * 26,
    endedAt: Date.now() - 1000 * 60 * 60 * 25,
  },
  {
    id: 'h-3',
    presetName: 'Ocean Meditation',
    presetId: 'community-5',
    mix: [{ soundId: 'ocean', volume: 0.9 }],
    duration: 10 * 60,
    startedAt: Date.now() - 1000 * 60 * 60 * 48,
    endedAt: Date.now() - 1000 * 60 * 60 * 47.8,
  },
  {
    id: 'h-4',
    presetName: 'Café Sessions',
    presetId: 'community-4',
    mix: [
      { soundId: 'coffee', volume: 0.8 },
      { soundId: 'piano', volume: 0.3 },
    ],
    duration: 52 * 60,
    startedAt: Date.now() - 1000 * 60 * 60 * 72,
    endedAt: Date.now() - 1000 * 60 * 60 * 71,
  },
  {
    id: 'h-5',
    presetName: 'Deep Focus',
    presetId: 'community-1',
    mix: [
      { soundId: 'rain', volume: 0.7 },
      { soundId: 'brown', volume: 0.4 },
    ],
    duration: 25 * 60,
    startedAt: Date.now() - 1000 * 60 * 60 * 96,
    endedAt: Date.now() - 1000 * 60 * 60 * 95.5,
  },
  {
    id: 'h-6',
    presetName: 'Morning Birds',
    mix: [
      { soundId: 'birds', volume: 0.75 },
      { soundId: 'forest', volume: 0.5 },
    ],
    duration: 30 * 60,
    startedAt: Date.now() - 1000 * 60 * 60 * 120,
    endedAt: Date.now() - 1000 * 60 * 60 * 119.5,
  },
  {
    id: 'h-7',
    presetName: 'Storm at Sea',
    presetId: 'community-6',
    mix: [
      { soundId: 'thunder', volume: 0.6 },
      { soundId: 'ocean', volume: 0.7 },
    ],
    duration: 60 * 60,
    startedAt: Date.now() - 1000 * 60 * 60 * 144,
    endedAt: Date.now() - 1000 * 60 * 60 * 143,
  },
];
